---
name: Molecule
description: Molecule is a tool to test ansible playbooks
author: amine7777

branding:
  icon: play
  color: green

inputs:
  command:
    description: Command to pass to molecule
    required: true
    default: molecule test

  working_dir:
    description: |
      Path to another directory in the repository, where molecule command will be issued from.
      Useful in those cases where Ansible roles are not in git repository root.
    required: false
    default: ${{ github.repository }}

runs:
  using: docker
  image: 'docker://amine7777/molecule-action:latest'