---
name: Molecule
description: Molecule is a tool to test ansible playbooks
author: amine7777

branding:
  icon: play
  color: green

inputs:
  options:
      description: Options to pass to molecule such as --debug to enable debug mode
      required: false

  command:
    description: Command to pass to molecule, for example, lint, converge, idempotence, test or verify.
    required: true
    default: test
  args:
    description: Arguments to pass to molecule such as --scenario-name to target a specific scenario
    required: false

  working_dir:
    description: |
      Path to another directory in the repository, where molecule command will be issued from.
      Useful in those cases where Ansible roles are not in git repository root.
    required: false
    default: ${{ github.repository }}

runs:
  using: docker
  image: 'docker://amine7777/molecule-action:latest'