---
- name: Converge
  hosts: all
  tasks:
    - name: "Include molecule-action"
      file:
        path: /tmp/newwwww
        state: directory
    
    - name: check folder
      command: ls -la /tmp
      changed_when: false
