on: [push]

jobs:
  molecule:
    runs-on: ubuntu-latest
    name: molecule 
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}

      - name: Create a scenario
        uses: amine7777/molecule-action@v1
        with:
          command: molecule init scenario
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: molecule test
        uses: amine7777/molecule-action@v1
        with:
          command: molecule test  
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      